// Code generated by hertz generator.

package socialize

import (
	"TikTok/biz/router/auth"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return auth.Auth()
}

func _socializeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _followMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryfollowlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryfollowerlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryfriendlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _followerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _followingMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _friendsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _relationMw() []app.HandlerFunc {
	// your code...
	return nil
}
