// Code generated by hertz generator.

package interact

import (
	"TikTok/biz/router/auth"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return auth.Auth()
}

func _interactMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletecommentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _hitlikebuttonMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _querycommentlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _querylikelistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _commentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _likeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _commentvideoMw() []app.HandlerFunc {
	// your code...
	return nil
}
