// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	interact "TikTok/biz/router/interact"
	model "TikTok/biz/router/model"
	socialize "TikTok/biz/router/socialize"
	user "TikTok/biz/router/user"
	video "TikTok/biz/router/video"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	interact.Register(r)

	socialize.Register(r)

	video.Register(r)

	user.Register(r)

	model.Register(r)
}
